config/routes.rb
Plate::Application.routes.draw do
  get "front/index"
  get "front/markup"
  get "front/form"
  get "front/signin"

  root :to => 'front#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  def index
  end

  def markup
  end

  def form
  end

  def signin
    render :layout => "skeleton"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    content_for?(:page_title) ? "Plate - #{content_for(:page_title)}" : "Plate - A simple rails boilerplate thingy"
  end

  def page_description
    (content_for?(:page_description) && content_for(:page_description)) \
      || "A template app as a boilerplate starting point for future apps"
  end

  def page_keywords
    (content_for?(:page_keywords) && content_for(:page_keywords)) \
      || "template, rails, compass, css, susy, fluid, fixed width, elastic, html5, css3, grid system, grid framework"
  end

  def page_scripts
    content_for(:page_scripts)
  end

  def input_field(&block)
    content_tag(:p, &block)
  end
end

app/helpers/front_helper.rb
module FrontHelper
end

app/views/front/form.html.erb
<h1>Sample Form</h1>

<%= form_tag :url => root_path do |form| -%>
  <fieldset>
    <legend>Common Fields</legend>

    <%= input_field do -%>
      <%= label_tag :field1, "Field 1" %>
      <%= text_field_tag :field1 %>
    <% end %>

    <%= input_field do -%>
      <%= label_tag :field2, "Field 2" %>
      <%= text_field_tag :field2 %>
    <% end %>

    <%= input_field do -%>
      <%= label_tag :password, "Password" %>
      <%= password_field_tag :password %>
    <% end %>

    <%= input_field do -%>
      <%= label_tag :field3, "Select Field" %>
      <%= select_tag :field3, options_for_select(["Option 1", "Option 2", "Option 3"]) %>
    <% end %>

    <%= input_field do -%>
      <%= check_box_tag :checkbox1 %>
      <%= label_tag :checkbox1, "Check this for nothing" %>
    <% end %>

    <%= input_field do -%>
      <%= radio_button_tag :radio, :radio1 %>
      <%= label_tag :radio_radio1, "Radio 1" %>

      <%= radio_button_tag :radio, :radio2 %>
      <%= label_tag :radio_radio2, "Radio 2" %>

      <%= radio_button_tag :radio, :radio3 %>
      <%= label_tag :radio_radio3, "Radio 3" %>
    <% end %>

    <%= input_field do -%>
      <%= label_tag :field4, "Text Area" %>
      <%= text_area_tag :field4 %>
    <% end %>
  </fieldset>

  <fieldset>
    <legend>HTML5 Fields</legend>

    <%= input_field do -%>
      <%= label_tag :email, "Email" %>
      <%= email_field_tag :email %>
    <% end %>

    <%= input_field do -%>
      <%= label_tag :url, "URL" %>
      <%= url_field_tag :url %>
    <% end %>

    <%= input_field do -%>
      <%= label_tag :telephone, "Telephone" %>
      <%= telephone_field_tag :telephone %>
    <% end %>

    <%= input_field do -%>
      <%= label_tag :range, "Range" %>
      <%= range_field_tag :range %>
    <% end %>

    <%= input_field do -%>
      <%= label_tag :number, "Number" %>
      <%= number_field_tag :number %>
    <% end %>

    <%= input_field do -%>
      <%= label_tag :phone, "Phone" %>
      <%= phone_field_tag :phone %>
    <% end %>

    <%= input_field do -%>
      <%= label_tag :search, "Search" %>
      <%= search_field_tag :search %>
    <% end %>

  </fieldset>

  <%= submit_tag "Submit" %>
<% end -%>

app/views/front/index.html.erb
<% content_for :sidebar do -%>
  <p>What a lovely sidebar!</p>

  <ul>
    <li>Let's</li>
    <li>list</li>
    <li>our</li>
    <li>feelings</li>
  </ul>
<% end -%>

<h1>Front Page</h1>

<p>Welcome to the front page. Here's a paragraph holding a bottle of Old Spice Body Wash. On a horse.</p>

<p><%= image_tag "old-spice-man.png" %></p>

<h2>Links of Interest</h2>

<ol>
  <li><%= link_to "A Large Page Of Markup", front_markup_path %> - Various html tags are displayed for styling</li>
  <li><%= link_to "A Big Bad Form", front_form_path %> - What does a form look like with every input control available?</li>
</ol>

<h2>And just for filler...</h2>

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis velit ligula. Donec congue elit et nibh aliquet commodo. Quisque diam est, tincidunt a mattis in, lacinia in mauris. Maecenas adipiscing sollicitudin ante, sit amet scelerisque orci rutrum id. Integer ac ultricies orci. Sed vel justo leo. Praesent quis eros leo. Quisque ornare faucibus sapien, nec scelerisque orci sagittis nec. Nullam laoreet, dui nec placerat gravida, tellus eros bibendum dolor, vitae fermentum ligula elit a ligula. Nulla nec enim et arcu cursus tincidunt.
</p>

app/views/front/markup.html.erb
<% content_for :page_title, "A sampling of markup" -%>

<h1>Header 1</h1>

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis velit ligula. Donec congue elit et nibh aliquet commodo. Quisque diam est, tincidunt a mattis in, lacinia in mauris. Maecenas adipiscing sollicitudin ante, sit amet scelerisque orci rutrum id. Integer ac ultricies orci. Sed vel justo leo. Praesent quis eros leo. Quisque ornare faucibus sapien, nec scelerisque orci sagittis nec. Nullam laoreet, dui nec placerat gravida, tellus eros bibendum dolor, vitae fermentum ligula elit a ligula. Nulla nec enim et arcu cursus tincidunt.
</p>

<p>
Donec massa felis, blandit ac porttitor ut, interdum suscipit nisl. Praesent id turpis a purus luctus semper quis sed augue. Quisque metus arcu, venenatis vel tincidunt eu, porttitor eget lacus. Donec aliquet accumsan lorem, ut tempor magna tempor in. Integer commodo, dui id luctus condimentum, mi nisl tincidunt justo, eu laoreet felis diam luctus purus. Ut ac urna at nisi porttitor consectetur eu vitae tortor. Mauris non quam nisi, eget iaculis felis. Cras nec mi magna, ac pellentesque tellus. Ut nisl velit, iaculis eu lobortis ac, bibendum nec nisl. Nullam eu urna quis dolor tempus vehicula. Donec vitae libero sed nisi consequat elementum nec sit amet urna. Aliquam aliquet porttitor nisi, vitae tincidunt lectus iaculis sed. Nam pharetra mauris sit amet diam vehicula eu vestibulum quam tincidunt. Nam tempor rutrum nunc, non tempor dolor porttitor vitae. 
</p>

<h2>Header 2</h2>

<ul>
  <li>UL item 1</li>
  <li>UL item 2</li>
  <li>UL item 3</li>
</ul>

<p>
Here is a paragraph with a few <%= link_to "links", "#" %>. There's one <%= link_to "here", "#" %> and another one for <%= link_to "Ruby on Rails", "http://rubyonrails.org" %>. Here is some <strong>strong text</strong> along with some <b>b-tag action</b>. Now we'll do <em>emphasized text</em> and even some <em><strong>strong emphasized text</strong></em>. Now some <sup>sup action</sup> followed by <sub>sub action</sub>.
</p>

<p>
Here's the #fun main loop:
<code>
  for (int i = 0; i &lt; MAX_FUN; i++) {
    rave_it_up();
    feel_down();
    feel_flat();
    plan_next_event();
  }
</code>
</p>

<p>
Here it is again as a block:
<p>

<pre>
for (int i = 0; i &lt; MAX_FUN; i++) {
  rave_it_up();
  feel_down();
  feel_flat();
  plan_next_event();
}
</pre>

<ol>
  <li>OL item 1 with a <code>term</code></li>
  <li>OL item 2</li>
  <li>OL item 3</li>
</ol>

<h3>Header 3</h3>

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis velit ligula. Donec congue elit et nibh aliquet commodo. Quisque diam est, tincidunt a mattis in, lacinia in mauris. Maecenas adipiscing sollicitudin ante, sit amet scelerisque orci rutrum id. Integer ac ultricies orci. Sed vel justo leo. Praesent quis eros leo. Quisque ornare faucibus sapien, nec scelerisque orci sagittis nec. Nullam laoreet, dui nec placerat gravida, tellus eros bibendum dolor, vitae fermentum ligula elit a ligula. Nulla nec enim et arcu cursus tincidunt.
</p>

<blockquote>
BLOCKQUOTE: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis velit ligula. Donec congue elit et nibh aliquet commodo. Quisque diam est, tincidunt a mattis in, lacinia in mauris. Maecenas adipiscing sollicitudin ante, sit amet scelerisque orci rutrum id. Integer ac ultricies orci. Sed vel justo leo. Praesent quis eros leo. Quisque ornare faucibus sapien, nec scelerisque orci sagittis nec. Nullam laoreet, dui nec placerat gravida, tellus eros bibendum dolor, vitae fermentum ligula elit a ligula. Nulla nec enim et arcu cursus tincidunt. 
</blockquote>

<dl>
  <dt>Definition list</dt>
  <dd>A list that I never use.</dd>

  <dt>HAML</dt>
  <dd>A template language I never use because it's WEIRD.</dd>

  <dt>SASS</dt>
  <dd>A template language that I USE THE SHIT OUT OF (preposition at).</dd>
</dl>

<h4>Header 4</h4>

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis velit ligula. Donec congue elit et nibh aliquet commodo. Quisque diam est, tincidunt a mattis in, lacinia in mauris. Maecenas adipiscing sollicitudin ante, sit amet scelerisque orci rutrum id. Integer ac ultricies orci. Sed vel justo leo. Praesent quis eros leo. Quisque ornare faucibus sapien, nec scelerisque orci sagittis nec. Nullam laoreet, dui nec placerat gravida, tellus eros bibendum dolor, vitae fermentum ligula elit a ligula. Nulla nec enim et arcu cursus tincidunt.
</p>

<h5>Header 5</h5>

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis velit ligula. Donec congue elit et nibh aliquet commodo. Quisque diam est, tincidunt a mattis in, lacinia in mauris. Maecenas adipiscing sollicitudin ante, sit amet scelerisque orci rutrum id. Integer ac ultricies orci. Sed vel justo leo. Praesent quis eros leo. Quisque ornare faucibus sapien, nec scelerisque orci sagittis nec. Nullam laoreet, dui nec placerat gravida, tellus eros bibendum dolor, vitae fermentum ligula elit a ligula. Nulla nec enim et arcu cursus tincidunt.
</p>

<h6>Header 6</h6>

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis velit ligula. Donec congue elit et nibh aliquet commodo. Quisque diam est, tincidunt a mattis in, lacinia in mauris. Maecenas adipiscing sollicitudin ante, sit amet scelerisque orci rutrum id. Integer ac ultricies orci. Sed vel justo leo. Praesent quis eros leo. Quisque ornare faucibus sapien, nec scelerisque orci sagittis nec. Nullam laoreet, dui nec placerat gravida, tellus eros bibendum dolor, vitae fermentum ligula elit a ligula. Nulla nec enim et arcu cursus tincidunt.
</p>

<p>Now for some tables</p>

<table cellspacing="0">
  <thead>
    <tr>
      <th>HEADER 1</th>
      <th>HEADER 2</th>
      <th>HEADER 3</th>
    </tr>
  </thead>
  <tr>
    <td>CELL 1 1</td>
    <td>CELL 1 2</td>
    <td>CELL 1 3</td>
  </tr>
  <tr>
    <td colspan="2">SPANAGE!</td>
    <td>CELL 2 3</td>
  </tr>
  <tr>
    <td rowspan="2">RAGGED!</td>
    <td>CELL 3 2</td>
    <td>CELL 3 3</td>
  </tr>
  <tr>
    <td>CELL 4 2</td>
    <td>CELL 4 3</td>
  </tr>
</table>

app/views/layouts/application.html.erb
<% content_for :body do -%>

<section id="header-page">
  <header class="container">
    <div class="logo">
      <h1>
        <%= link_to "Plate", root_path %>
      </h1>
      <h2>
        It's what's for dinner
      </h2>
    </div>
    <nav id="top-nav">
      <ul class="inline-nav-menu">
        <li><%= link_to "Home", root_path %></li>
        <li>
          <%= link_to "Dropdown", "#" %>
          <ul>
            <li><%= link_to "Item 1", "#" %></li>
            <li><%= link_to "Item 2", "#" %></li>
            <li><%= link_to "Item 3", "#" %></li>
          </ul>
        </li>
        <li class="clickdown">
          <%= link_to "Clickdown", "#" %>
          <ul>
            <li><%= link_to "Google", "http://google.com" %></li>
            <li><%= link_to "Apple", "http://apple.com" %></li>
            <li><%= link_to "Item 3 that's really really really really really long", "#" %></li>
          </ul>
        </li>
      </ul>
    </nav>
    <nav id="bar-nav">
      <ul class="nav-menu">
        <li><%= link_to "Sign In", front_signin_path %></li>
        <li>
          <%= link_to "Drop 2", "#" %>
          <ul>
            <li><%= link_to "Item 1", "#" %></li>
            <li><%= link_to "Item 2", "#" %></li>
            <li><%= link_to "Item 3", "#" %></li>
          </ul>
        </li>
        <li><%= link_to "Link 3", "#" %></li>
        <li class="clickdown">
          <%= link_to "Click 4", "#" %>
          <ul>
            <li><%= link_to "Item 1", "#" %></li>
            <li><%= link_to "Item 2", "#" %></li>
            <li><%= link_to "Item 3", "#" %></li>
          </ul>
        </li>
        <li><%= link_to "Link 5", "#" %></li>
        <li><%= link_to "Link 6", "#" %></li>
      </ul>
    </nav>
  </header>
</section>

<section id="main-page">
  <div id="main-content" class="container <%= content_for?(:sidebar) ? "two-column" : "full-page" %>">
    <section id="main" class="primary">
      <%= yield %>
    </section>
    <% if content_for?(:sidebar) -%>
      <div id="sidebar" class="sidebar">
        <section id="sidebar-content">
          <%= yield :sidebar %>
        </section>
      </div>
    <% end -%>
  </div>
</section>

<section id="footer-page">
  <footer class="container">
    <section class="links">
      <ul>
        <li><%= link_to "The more links", "#" %></li>
        <li><%= link_to "in the footer", "#" %></li>
        <li><%= link_to "the more likely", "#" %></li>
        <li><%= link_to "we'll get funded", "#" %></li>
        <li><%= link_to "amirite? Of course!", "#" %></li>
      </ul>
      <ul>
        <li><%= link_to "But you need", "#" %></li>
        <li><%= link_to "a lot of links", "#" %></li>
        <li><%= link_to "because otherwise", "#" %></li>
        <li><%= link_to "how will you be", "#" %></li>
        <li><%= link_to "considered a big deal?", "#" %></li>
      </ul>
      <ul class="last">
        <li><%= link_to "So link away!", "#" %></li>
        <li><%= link_to "They can be anything", "#" %></li>
        <li><%= link_to "It's not like anyone", "#" %></li>
        <li><%= link_to "Looks at the actual content", "#" %></li>
        <li><%= link_to "Do they?", "#" %></li>
      </ul>
    </section>
    <span class="copyright">Copyright © Jeff Siegel</span>
  </footer>
</section>

<% end -%>
<%= render :file => 'layouts/skeleton' %>

app/views/shared/_grid_control.html.erb
<div class="grid-control">
  <%= link_to "Show Grid", "#", :id => "show-grid" %>
  <%= link_to "Hide Grid", "#", :id => "hide-grid", :class => "hidden" %>
</div>

<% content_for :page_scripts do -%>
  <script type="text/javascript">
    $(document).ready(function() {
      $("#.grid-control a").click(function() {
        $(".grid-control a").toggleClass("hidden");
        $("header, #main-content, footer, #dialog-container").toggleClass("show-grid");
        return false;
      });
    });
  </script>
<% end -%>